apiVersion: v1
kind: ConfigMap
metadata:
  name: kubeconfig-template
  namespace: production
data:
  kubeconfig-template.yaml: |
    apiVersion: v1
    kind: Config
    clusters:
    - name: ${CLUSTER_NAME}
      cluster:
        certificate-authority: /certs/ca.crt
        server: https://${KUBERNETES_SERVICE_HOST}:${KUBERNETES_SERVICE_PORT}

    users:
    - name: ${KUBE_USER}
      user:
        client-certificate: /certs/client.crt
        client-key: /certs/client.key

    contexts:
    - name: ${CONTEXT_NAME}
      context:
        cluster: ${CLUSTER_NAME}
        user: ${KUBE_USER}

    current-context: ${CONTEXT_NAME}
