apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: prod-rolebinding-manager
  namespace: production
rules:
  - apiGroups: ["rbac.authorization.k8s.io"]
    resources:
      - rolebindings
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
  - apiGroups: ["rbac.authorization.k8s.io"]
    resources:
      - roles
    verbs:
      - bind
