---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: developer
  namespace: development
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: developer-portforward
  namespace: development
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["list", "get"]
  - apiGroups: [""]
    resources: ["pods/portforward"]
    verbs: ["create"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: developer-portforward-rb
  namespace: development
subjects:
  - kind: ServiceAccount
    name: developer
    namespace: development
roleRef:
  kind: Role
  name: developer-portforward
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: Secret
metadata:
  name: developer-token
  namespace: development
  annotations:
    kubernetes.io/service-account.name: developer
type: kubernetes.io/service-account-token
